### ISSUE TITLE
Include Username in Blog Slug

### ISSUE THREAD

**Issue by Mirror83** [Rontim/MyCampus-backend#10]
Include the blog username in the slug, so that different authors can have blogs with the same title. Currently, the slug only includes the title of the blogs.

**Comment by Rontim** [comment]
Okay the logic, in the blog model, there are three fields; author type, author user and author club, so we will check what the  other type is and update accordingly and save the slug before creation
```python
def save(self, *args, **kwargs):
    base_slug = self.title
    if self.author_type == "user":
        base_slug += f' {self.author_user.username}'
    if self.author_type == "club":
        base_slug += f' {self.author_club.club_name}'
    self.slug = slugify(base_slug)
    super().save(*args, **kwargs)
```

**Comment by Rontim** [comment]
@muceraaa  please handle that:

1. create the branch for this issue
2. checkout into that branch locally
3. Happy coding
